[phases.setup]
nixPkgs = [
  "python311",
  "libjpeg",
  "libpng",
  "freetype",
  "zlib",
  "libwebp"
]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "cd src && python main.py"
