[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "libjpeg",
  "libpng",
  "freetype",
  "zlib",
  "libwebp",
  "postgresql",
  "dejavu_fonts",
  "fontconfig"
]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "cd src && python main.py"
